# This workflow builds pull-requests but does not merge them
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull-Request Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Learn
      run: cat $GITHUB_EVENT_PATH
    - name: Checkout PR HEAD
      uses: actions/checkout@v2
      with:
          ref: ${{ github.event.pull_request.head.sha }}
    - name: Checkout destination branch
      run: echo git checkout $GITHUB_BASE_REF
    - name: Merge to destination branch
      run: echo git merge --no-ff -m "Merge PR ${{ github.event.pull_request.number }}"
    - run: git show --summary

      #   - name: Set up JDK 11
      #     uses: actions/setup-java@v2
      #     with:
      #       java-version: '11'
      #       distribution: 'adopt'
      #   - name: Grant execute permission for gradlew
      #     run: chmod +x gradlew
      #   - name: Build with Gradle
      #     run: ./gradlew test
