# This workflow builds pull-requests but does not merge them
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pull-Request Build

on:
    issue_comment:
        types: [created]

jobs:
  build-pull-request:
    name: Run tests
    # if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/test') }}
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/test' }}

    runs-on: ubuntu-latest

    steps:

        # Some steps for learning and for debug
        #- name: github.event.issue.pull_request (debug)
        #  env:
        #      PR: ${{ toJSON(github.event.issue.pull_request) }}
        #  run: echo "-- $PR --"
        #- name: github.event.comment.body (debug)
        #  env:
        #      COMMENT: ${{ toJSON(github.event.comment.body) }}
        #  run: echo "-- $COMMENT --"
        #- name: GITHUB_EVENT_PATH (debug)
        #  run: cat $GITHUB_EVENT_PATH
        #- name: curl pull request url (debug)
        #  run: curl -s -X GET ${{ github.event.issue.pull_request.url }}

        - name: Get PR context
          id: pr-context
          uses: actions/github-script@v4.1.0
          with:
              # the return value is always a string, even when set to "json"
              result-encoding: json
              script: |
                  const response = await github.pulls.get({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      pull_number: context.payload.issue.number
                  });
                  console.log(response)
                  return response

        # Update the PR status check by posting to the PR head sha
        # job.status can be success, failure or cancelled
        # See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-context
        # Status functions are always(), success(), failure(), cancelled()
        # See: https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions
        # The POSTed state can be error, failure, pending or success
        # See https://docs.github.com/en/rest/reference/repos#create-a-commit-status
        - name: Update status to pending
          run: |
              curl -X POST -v \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header "Accept: application/vnd.github.v3+json" \
              --data '{
                  "context": "build-pull-request",
                  "state": "pending",
                  "description": "build-pull-request pending",
                  "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }' \
              --url 'https://api.github.com/repos/${{ github.repository }}/statuses/${{ fromJSON(steps.pr-context.outputs.result).data.head.sha }}' \
              --fail

        # Examples of the different ways to use the pr-context json string
        #- name: Examine pr-context
        #  env:
        #      PR1: ${{ toJSON(steps.pr-context.outputs) }}
        #      PR2: ${{ toJSON(steps.pr-context.outputs.result) }}
        #      PR3: ${{ fromJSON(steps.pr-context.outputs.result).status }}
        #      PR4: ${{ fromJSON(steps.pr-context.outputs.result).data.base.ref }}
        #      PR5: ${{ toJSON(fromJSON(steps.pr-context.outputs.result).data) }}
        #  run: |
        #      echo "PR3: $PR3"
        #      echo "PR4: $PR4"
        - name: Checkout the merge commit
          uses: actions/checkout@v2
          with:
              # Use either fetch-depth: 0 and manually merge, or reference the merge_commit_sha
              ref: ${{ fromJSON(steps.pr-context.outputs.result).data.merge_commit_sha }}

        # Manually merge the PR - don't use if referencing a checkout commit above because it will be shallow
        #- name: Fetch the pull-request
        #  run: git fetch origin +refs/pull/${{ github.event.issue.number }}/head:refs/remotes/origin/pr/${{ github.event.issue.number }}
        #- name: Switch to the PR branch
        #  run: git switch pr/${{ github.event.issue.number }}
        #- name: Fetch the destination branch
        #  run: git fetch origin ${{ fromJSON(steps.pr-context.outputs.result).data.base.ref }}
        #- name: Switch to destination branch
        #  run: git switch ${{ fromJSON(steps.pr-context.outputs.result).data.base.ref }}

        # Examining the git log before manually merging (for debug)
        - name: Git log
          run: |
              git log --format=format:"%C(auto)%h %C(cyan)%ar%C(auto) %d %C(green)%aN%Creset %s" --graph --all -n 15

        # Manually merge the PR
        #- name: Merge PR into destination branch
        #  run: |
        #      git config --local user.email "action@github.com"
        #      git config --local user.name "GitHub Action"
        #      git merge --no-ff -m "Merge PR ${{ github.event.issue.number }} to ${{ fromJSON(steps.pr-context.outputs.result).data.base.ref }}" pr/${{ github.event.issue.number }}

        # Examine the merge commit (debug)
        - name: Show summary
          run: git show --summary

        # Now to the point of the build
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: 'gradle'

        - name: Grant execute permission for gradlew
          run: |
              chmod +x gradlew
              ./gradlew test --console=plain --no-daemon

        - name: Publish Test Report
          uses: mikepenz/action-junit-report@v2
          if: always() # always run even if the previous step fails
          with:
              report_paths: '**/build/test-results/test/TEST-*.xml'

        - name: Compute status string
          id: get-build-status
          # When cancelled, the PR status remains pending
          if: ${{ success() || failure() }}
          outputs:
              statusString:
                  description: 'The status string value of the build for the REST API'
                  value: ${{ job.status }}

        - name: Update status
          # When cancelled, the PR status remains pending
          if: ${{ success() || failure() }}
          run: |
              curl -X POST -v \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header "Accept: application/vnd.github.v3+json" \
              --data '{
                  "context": "build-pull-request",
                  "state": "${{ steps.get-build-status.outputs.statusString }}",
                  "description": "build-pull-request ${{ steps.get-build-status.outputs.statusString }}",
                  "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }' \
              --url 'https://api.github.com/repos/${{ github.repository }}/statuses/${{ fromJSON(steps.pr-context.outputs.result).data.head.sha }}' \
              --fail
