/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.martinda;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Hello Again");
        System.out.println("Hello 2");
        System.out.println("Hello 3");
        System.out.println("Hello 4");
    }
}
